name: kafka-dotnet-ci

on:
  push:
    branches: 
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      kafka:
        image: bitnami/kafka:latest
        ports: 
          - 9092:9092
        env:
          KAFKA_KRAFT_MODE: "true"
          KAFKA_CFG_NODE_ID: 1
          KAFKA_CFG_PROCESS_ROLES: "broker,controller"
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
          KAFKA_CFG_LISTENERS: "PLAINTEXT://:29092,EXTERNAL://:9092,CONTROLLER://:9093"
          KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
          KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
          ALLOW_PLAINTEXT_LISTENER: "yes"
        options: --health-cmd="bash -c 'echo > /dev/tcp/localhost/9092'" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
