name: kafka-dotnet-ci

on:
  push:
    branches: master

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      kafka:
        image: bitnami/kafka:latest
        ports: 
          - 9092:9092
        options: "--health-cmd=\"curl -f localhost:9092 || exit 1\" --health-interval=10s --health-timeout=5s --health-retries=5"

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
