name: kafka-dotnet-ci

on:
  push:
    branches: master

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      kafka:
        image: bitnami/kafka:latest
        ports: 
          - 9092:9092
        env:
          KAFKA_KRAFT_CLUSTER_ID: "abcdefghijklmnopqrstuv"
          KAFKA_CFG_NODE_ID: 1
          KAFKA_CFG_PROCESS_ROLES: "broker,controller"
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
          KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
          KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
        options: "--health-cmd=\"curl -f localhost:9092 || exit 1\" --health-interval=10s --health-timeout=5s --health-retries=5"

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
